// @ts-check
// 「LLM 隐私保护」主题（第二 docs 实例 id=privacy）的侧边栏。
// 与第一个主题一样让 Docusaurus 按目录结构自动生成：阅读主线按 LLM 演进史分「卷」，
// 各卷的中文标签与排序由 privacy/**/_category_.json 控制。详见 PROPOSAL-privacy-book.md §6.1。

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  privacySidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

module.exports = sidebars;
