// @ts-check
// 侧边栏：让 Docusaurus 按目录结构自动生成（生命周期阶段为主线）。
// 各阶段的中文标签与排序由 docs/**/_category_.json 控制。

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  wikiSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

module.exports = sidebars;
